# ci pipeline for auth service
name: auth-ci
on: 
    push:
        branches:
            - main
        paths:
            - 'auth/**'
    pull_request:
        branches:
            - main
        paths:
            - 'auth/**'
jobs:
    build: 
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: auth
        steps:
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: checkout the code
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm install
            - name: build the ts files
              run: npm run build 
            - name: storing the build files as artifacts
              uses: actions/upload-artifact@v4
              with:
                name: auth-build
                path: |
                    auth/dist/**
                    auth/package.json
                    auth/package-lock.json
                    auth/docker/**
            - name: debug
              run: ls -R 
    test:
        needs: build
        runs-on: ubuntu-latest
        env:
            MONGODB_USERNAME: ${{secrets.MONGODB_USERNAME}}
            MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
            MONGOUI_UI_USERNAME: ${{secrets.MONGOUI_UI_USERNAME}}
            MONGO_UI_PASSWORD: ${{secrets.MONGO_UI_PASSWORD}}
            REDIS_PASS: ${{secrets.REDIS_PASS}}
        defaults:
            run:
                working-directory: auth
        steps:
            - uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: download the build files
              uses: actions/download-artifact@v4
              with:
                name: auth-build
                path: auth/dist
            - name: debug files
              run: | 
                echo "PWD:" 
                pwd
                echo "directories: " 
                ls
                cd dist
                echo "directory inside dist: "
                ls -R
            - name: install dependencies
              run: npm install --omit=dev
            - name: start docker compose
              run: cd docker && docker compose up -d
            - name: wait for app to be up and running
              run: sleep 20
            - name: checking if the docker containers are running 
              run: docker ps -a
            - name: starting the server
              run: npm start & # start the server in the background
            - name: wait for server to be healthy
              run: sleep 5
            - name: checking if app is running
              run: |
                for i in {1..5}; do
                  STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/api/v1/health)
                  if [ "$STATUS" -ne 200 ]; then
                    echo "Health check $i passed with status $STATUS. Retrying..."
                    exit 0
                  fi
                  echo "Health check $i failed with status $STATUS. Retrying in 5 seconds..."
                  sleep 5
                done
            - name: cleanup
              if: always()
              run: cd docker && docker compose down            
